Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 50
